[tool.bumpversion]
current_version = "2.0.0"
commit = true
tag = true

[[tool.bumpversion.files]]
filename = "plugin.yaml"
search = "version: \"{current_version}\""
replace = "version: \"{new_version}\""
