name: "outdated"
version: "2.0.4"
usage: "Manage outdated dependencies of a helm chart"
description: "This plugin helps to find and update outdated dependencies of a helm chart"
command: "$HELM_PLUGIN_DIR/bin/helm-outdated-charts"
useTunnel: false
hooks:
  install: "cd $HELM_PLUGIN_DIR; ./install_plugin.sh"
  update: "cd $HELM_PLUGIN_DIR; ./install_plugin.sh"
