name: Build
on:
  push: {}
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  build-helm-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - name: Build
        run: task build
