name: release
on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  release-helm-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: arduino/setup-task@v2
      - uses: Homebrew/actions/setup-homebrew@master
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - run: task dev:tools:install
      - run: brew install yq
      - name: Build
        run: task build
      - name: Release
        run: task release
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
